### ISSUE TITLE
Composer problem

### ISSUE THREAD

**Issue by aariza-argentina** [alexwight/php-signalr-client#1]
Hi! 
How can install with composer?
Thanks!

**Comment by aariza-argentina** [comment]
I add 

`    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/alexwight/php-signalr-client"
        }
    ],
`

to composer.json and I get to work

Just a message about 

>  Package react/socket-client is abandoned, you should avoid using it. Use react/socket instead.

Thanks!

>

**Comment by alexwight** [comment]
Ah, I hadn't added it to packagist as I just used this for my own project and didn't get around to writing any documentation yet.  You can now just 
`composer require alexwight/php-signalr-client`
